### ISSUE TITLE
insert physiological data

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/eurobench_documentation#12]
They somehow disappear

**Comment by FraCampus** [comment]
we acquire data from physiological sensors , obtaining 4 different parameters: heart rate, heart rate variability, respiration rate and galvanic skin response.

can these be added as data format somehow (as Pre-processed one)? We think that CSV files may work and we expect to have a structure like:  timestamp; value (nx2, with n being number of samples)

ping @NevioTag

**Comment by aremazeilles** [comment]
Could you detail the format for each of the 4 measures you mention?

**Comment by aremazeilles** [comment]
[Physiological Data Format.pdf](https://github.com/aremazeilles/eurobench_documentation/files/4520574/Physiological.Data.Format.pdf)

**Comment by aremazeilles** [comment]
In my opinion, the rationale for preferring a data per file, or a joint file with all data, is whether all these measures are usually measured by the same device. In your case I guess this is true, right? What is your opinion?

**Comment by aremazeilles** [comment]
Wrt the description, I would be in favour of placing more detailed information, like:

* Heart rate:
  * is the speed of the heartbeat measured by the number of contractions (beats) of the heart per minute (bpm)
  * link: https://en.wikipedia.org/wiki/Heart_rate
  * label: hr
* Heart rate variability:
  * (HRV) is the physiological phenomenon of variation in the time interval between heartbeats. It is measured by the variation in the beat-to-beat interval.
  * Link: https://en.wikipedia.org/wiki/Heart_rate_variability
  * label: hrv 
* Respiration rate:
  * the rate at which breathing occurs
  * link: https://en.wikipedia.org/wiki/Respiratory_rate 
  * label : rr? 
* Galvanic skin response:
  * refers to changes in sweat gland activity that are reflective of the intensity of our emotional state
  * link: https://en.wikipedia.org/wiki/Electrodermal_activity or https://imotions.com/blog/gsr/
  * label: gsr

**Comment by aremazeilles** [comment]
Globally speaking, I think we prefer having timestamp in sec and not ms (to be confirmed).

Going one after the other...

**BPM**: at each instant the value recorded is the estimation of the BPM, is that correct?

**Comment by alfonsotecnalia** [comment]
I would say timestamp should be in seconds.

Regarding the options for the file format, we should handle both. In order to reuse the data in other PIs, we could provide utils for merging several csv with physiological data into one (we should think how to make a unique timestamp/stablish common rate) and/or split into different files from a joint one.

**Comment by aremazeilles** [comment]
ping @DavideGiusino

**Comment by DavideGiusino** [comment]
As long as physiological measures are acquired by the same device starting from the same point in time (i.e., all four parameters are captured contemporarily by only one sensor), which I guess it is the case here, I think Option 2 would provide a less dispersed format, which I would prefer even to eventually make comparisons between parameters more easily. Although Option 1 is said to be more flexible in that one can decide to add new quantities in the future, what prevents from adding new quantities in Option 2? I guess you can still add quantities in the future in Option 2, is that right?

**Comment by aremazeilles** [comment]
Yep we can still extend format later on if needed, and yes haring the same timestamp is mandatory for bringing it to a common file.

**Comment by NevioTag** [comment]
> In my opinion, the rationale for preferring a data per file, or a joint file with all data, is whether all these measures are usually measured by the same device. In your case I guess this is true, right? What is your opinion?

In our case we acquire HR, HRV and RR from one device and GSR from a different device. We then synchronized them with a dedicated software.

**Comment by NevioTag** [comment]
> Globally speaking, I think we prefer having timestamp in sec and not ms (to be confirmed).
> 
> Going one after the other...
> 
> **BPM**: at each instant the value recorded is the estimation of the BPM, is that correct?

We used ms because we tool as reference example other data formats. But clearly for us also s is fine.

**Comment by aremazeilles** [comment]
If we gather format, we should provide a common name for it
I have the impression it makes sense gathering hr, hrv, rr. Do you think it makes also sense gathering with them the gsr?

Or should just gather the 4, and name the joint file `physiology` ?

**Comment by aremazeilles** [comment]
Have a look at the [proposed decsrption](https://github.com/aremazeilles/eurobench_documentation/blob/physiological/data_format.adoc#physiological-data)

Could you revise the description, and propose adjustment if needed? 
I would need also the unit of `hrv`, `rr` and `gsr`.

In that version I propose to gather all in a unique file. Then I am wondering whether the term _physiological_ could not gather other type of measures, even up to EMG ? Would this be true? In any case, I would not add in the same file EMG, but this is just to decide whether _physiological` is the appropriate term here.

**Comment by aremazeilles** [comment]
Guys, could you review the proposition ?
Alfonso nicely mentioned the following units:

> gsr- S(siemens) or uS(microsiemens)
> rr- bpm (breaths per minute)

Can you confirm?

**Comment by FraCampus** [comment]
> Guys, could you review the proposition ?
> Alfonso nicely mentioned the following units:
> 
> > gsr- S(siemens) or uS(microsiemens)
> > rr- bpm (breaths per minute)
> 
> Can you confirm?

We have the following units:
-gsr in mS (milliSiemens)
-rr in bpm (breaths per minute)
