### ISSUE TITLE
New data formats

### ISSUE THREAD

**Issue by SjoerdBruijn** [aremazeilles/eurobench_documentation#18]
For some of the code we are working on, we require; 
Full body CoM trajectory (nx3, with n being number of samples)
Full body angular momentum (calculated around CoM) (nx3, with n being number of samples)
Combined inertia of the body (inertia tensor of all segments combined) (nx3x3 with n being number of samples)

can these be added as data format somehow? We think that CSV files may work.

**Comment by aremazeilles** [comment]
adding colleagues to the discussion:  ping @flxalr @davidpintofernandez @alfonsotecnalia. 

Could  you confirm for each of the required format the related header? 
For the COM for instance I expect it to be `timestampt; X; Y, Z` correct? Could you suggest structure for the two following ones?

**Comment by SjoerdBruijn** [comment]
CoM: `timestampt, X, Y, Z`
AngMom: `timestampt, X, Y, Z`
FullBodyI: `timestampt, Xx, Xy, Xz, Yx, Yy, Yz, Zx, Zy, Zz`
another important thing (that I realise just now) to agree on would be what the different global axes directions are; for instance, we always use X as AP axis (pointing forward, in gait direction), Y pointing left, and Z up. The actual definition is of course arbitrary, but I think it's good to have a standard that says what the data should look like. It seems that this is not in place yet in the description? (or did I miss this? )

**Comment by m-lancini** [comment]
We usually have the X as AP axis and Y as the vertical axis (since many gait analysis models do not require the Z axis).
I think it would be best to employ existing standards, such as the one of the International Society of Biomechanics: see https://www.ncbi.nlm.nih.gov/pubmed/8550644 
ISB recommendations for standardization in the reporting of kinematic data.

**Comment by SjoerdBruijn** [comment]
I'm OK with any definition, but I think that one should be defined. The reason we use z as up is because it facilitates plotting in matlab, where the Z is also up in 3d figures. As said, it doesnt matter, but it matters because we shouldn't be using different definitions. I agree that the ISB definitions may be a smart way to go.

**Comment by m-lancini** [comment]
Completely agree, we should define the standard somewhere, for the global reference and for the bodies relative references as well.

**Comment by DavidPintoFernandez** [comment]
I completely agree that we have to define a standard, and also agree that the best solution is to adapt to what is already done and well extended, the ISB recommendations, as Matteo suggested.

**Comment by aremazeilles** [comment]
How would ou like to define that standard? Can somebody does it ? Or just pass me an example text, and I can start incorporate it?

**Comment by aremazeilles** [comment]
Apart from that axis direction, is that ok with you @DavidPintoFernandez to insert these other format?

If yes, I can work on it.

**Comment by flxalr** [comment]
Are we only talking about the three mentioned files (CoM, AngMom, FullBodyI)? I think that a conversion to a global reference frame is feasible.

Some questions for better understanding:
Do you record human motion plus exo-motion or just the motion of the human subject? Will the exo be considered in the computation of the CoM, angular momentum and full body inertia? Defining one reference frame for everything will get problematic if you want to export data based on the underlying model of the exo (or humanoid).

**Comment by SjoerdBruijn** [comment]
yes, we are only talking about CoM, angmom, and FullbodyI and these should all be expressed in a global frame. 
So far, we have done mostly human only testing. However, when doing human+exo, the properties of the exo need to be taken into account.

**Comment by aremazeilles** [comment]
Resuming discussion to move forward
> I think it would be best to employ existing standards, such as the one of the International Society of Biomechanics: see https://www.ncbi.nlm.nih.gov/pubmed/8550644
Do you refer to Figure 1 axis direction [on that paper](https://www.ece.uvic.ca/~bctill/papers/mocap/Wu_Cavanagh_1995.pdf)?

With respect to the 3 proposed types, CoM, AngMom, FullBodyI, should we add a short description sentence? So far we only have the one line description provided by Sjoerd:

> * Full body CoM trajectory (nx3, with n being number of samples)
> * Full body angular momentum (calculated around CoM) (nx3, with n being number of samples)
> * Combined inertia of the body (inertia tensor of all segments combined) (nx3x3 with n being number of samples)

**Comment by m-lancini** [comment]
> > I think it would be best to employ existing standards, such as the one of the International Society of Biomechanics: see https://www.ncbi.nlm.nih.gov/pubmed/8550644
> > Do you refer to Figure 1 axis direction [on that paper (https://www.ece.uvic.ca/~bctill/papers/mocap/Wu_Cavanagh_1995.pdf)?
> 
> With respect to the 3 proposed types, CoM, AngMom, FullBodyI, should we add a short description sentence? So far we only have the one line description provided by Sjoerd:

Yes, I'd go with that.. and I'd use the same standards to describe local relative references (the arm's the leg's... etc)

**Comment by aremazeilles** [comment]
@SjoerdBruijn and other, could you have a look at the proposition in branch [udbenchmark](https://github.com/aremazeilles/eurobench_documentation/blob/udbenchmark/data_format.adoc#body-center-of-mass-3d-trajectory), where I introduce the 3 formats?

I did put a reference for the 2 first one, could you check if you have more relevant references, and propose one for the inertia tensor?

Then I did not mention the axis direction. Should I do it in one of these format, or provide at the beginning of the section a general spec ?

@SjoerdBruijn can you confirm you update the inertia tensor at a given frequency?

**Comment by nickkluft** [comment]
The proposed formats seem to fit the udbenchmark project. 
For sake of consistency, it might be wise to use similar metric units (e.g. milliseconds instead of sec, and mm instead of m) in the proposed formats, and have the estimates in the global frame of reference. 

Regarding references, I would suggest to refer to Kinetics of Human Motion
By Vladimir M. Zatsiorsky.

**Comment by m-lancini** [comment]
I'd like to use seconds (s) and meters (m) instead of ms and mm since when adding also newtons (N) the idea of having a mN just to be consistent is confusing. But the important thing is to be explicit in that.
Concerning Kinetics of Human Motion I see it uses a different reference for the Y axis, please make sure that the reference system is rotated according to the ISB standard.

**Comment by aremazeilles** [comment]
I would also be in favour of seconds and meters. I created an issue to adjust other format.

Sjoerd mentioned earlier that the [ISB recommandation](https://www.ece.uvic.ca/~bctill/papers/mocap/Wu_Cavanagh_1995.pdf#2) would be ok for your protocol. I hope this is right.

I could mention it at the beginning of the data format section, with something like:

For any measurement involving a global reference frame, we consider this frame to be as proposed in the [ISB recommandations](https://www.ece.uvic.ca/~bctill/papers/mocap/Wu_Cavanagh_1995.pdf) :

* `x` axis is aligned with the gait direction
* `y` axis is vertical, and pointing upwards

**Comment by aremazeilles** [comment]
I added at the [begining](https://github.com/aremazeilles/eurobench_documentation/blob/udbenchmark/data_format.adoc#23-global-reference-frame) of the document a subsection on the default global reference frame.

Ready to be merged ?
