### ISSUE TITLE
joints angle file structure

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/eurobench_documentation#19]
Original:
> 1st row: header with M+1 labels were M = number of angles considered.

I think the text used for the torques is better understood:
>1st row: header with (3*M)+1 labels were M = number of joints.

**Comment by aremazeilles** [comment]
I have even wondering if it would be more self-explanatory to provide it as a table:

| time | joint_name_x | joint_name_y | joint_name_y | ... |
|-------------|----------------|----------------|---------------|---|
| 649290.20 | 0.02                | 0.551              | 0 |

What do you think?

**Comment by aremazeilles** [comment]
I would suggest using such example structure, in place of the whole text:

**File structure**:

* 1st column: time-stamp (units: milliseconds).
* 1st row: header with M+1 labels were M = number of angles considered.
* From 2nd row: angle values, each corresponding to one time sample.

**Header labels**: 1st-column label: “time”. All other labels: see ‘Angle definition’ section.

**Units**: Degrees

**Comment by DavidPintoFernandez** [comment]
@aremazeilles I agree, the table is self-explanatory and maybe it is easier to understand than the text. We should maintain the reference to the angle definition section for the joint labels.

**Comment by aremazeilles** [comment]
@alfonsotecnalia does it sound good to you as well (including the reference to joint label of course)? 
If so, I will make such change in all the format descriptions....

**Comment by alfonsotecnalia** [comment]
I agree, the table is easier to understad, avoids misunderstandings and naming of the fields is standardized. For example:
* 1st column: time-stamp (units: milliseconds): one can think in naming such colum time, other one timestamp, other ms_since_epoch...
With the table you know that the header of the first column should be time. Same with the name of angle components.
