### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/eurobench_documentation#2]
From me: 

> We are expecting to launch PI computation run per run. 
> Thinking of the folder that would contain all this information, it could be good having the files alphabetically ordered per run.

> That would thus require to change it to be something like:

`subject_N_run_R_jointAngles.csv`

> What do you think?

**Comment by diegotorricelli** [comment]
Good point, I agree

**Comment by aremazeilles** [comment]
@alfonsotecnalia do you agree, can I adjust the text in that direction (nd then, later on we would adjust the P Manager accordingly?)

**Comment by aremazeilles** [comment]
I start working on this

**Comment by alfonsotecnalia** [comment]
I already have a branch expecting the filenames in that way:
subject_N_run_R_jointAngles.csv

I planned to merge it with the master when the user trials finish.
