### ISSUE TITLE
Ground reaction forces

### ISSUE THREAD

**Issue by m-lancini** [aremazeilles/eurobench_documentation#22]
section 4.4. Ground Reaction Forces file states that the GRF file shall contain forces measured by force platforms.
We also measure GRFs from crutches, when they are used, so we have more GRFs.
Shall we save the GRFs of the crutches in the same file or shall we foresee a file template for reaction forces not at the feet? 
I imagine this is not limited to crutches but also instrumented steps and handrails also could express the forces between the pilot and the environment as reaction forces.

**Comment by aremazeilles** [comment]
Do you refer to force sensor (which provide force and  torque)? or do you get also, like in 4.4 information of force, moment & centre or pressure?

If we have force sensor, then I would rather another type of file.
What is your opinion?

**Comment by m-lancini** [comment]
Our raw data is made up by forces and orientations (since there is an IMU on the crutches), along with the gait phase and its uncertainty.
It could be a separate file, but I believe many testbed will be measuring forces acting as reactions so a standard could be set.

**Comment by aremazeilles** [comment]
It does not seem wrong to me distinguishing ground reaction forces, in which we assume we would get a center of pressure, and wrench sensors that would just provide  force and torque.

As an analogy, the similar structure in ROS would be the  [WrenchStamped](http://docs.ros.org/api/geometry_msgs/html/msg/WrenchStamped.html), that contains only force and torque.

So I would rather distinguish them

**Comment by alfonsotecnalia** [comment]
In the parser I was implementing, WrenchStamped messages were converted to Ground Reaction Forces format because there was no any other type containig forces/torques. Centre of pressure fields were left in blank. 
As you have commentd, I think it would be better to create a format for containing only force/torque information.
