### ISSUE TITLE
Multiple force sensors (naming convention)

### ISSUE THREAD

**Issue by m-lancini** [aremazeilles/eurobench_documentation#27]
What do we do in scenarios which contains multiple force sensors?
- One file per sensor: subject_N_run_R_wrench_sensor_1.csv, subject_N_run_R_wrench_sensor_2.csv, ..., subject_N_run_R_wrench_sensor_S.csv
- One file with fields differentiating the sensor the data come:  subject_N_run_R_wrench.csv

| time | sensor_1_force_x | sensor_1_force_y | sensor_1_force_z | sensor_1_torque_x | sensor_1_torque_y | sensor_1_torque_z | sensor_2_force_x | sensor_2_force_y | sensor_2_force_z | sensor_2_torque_x | sensor_2_torque_y | sensor_2_torque_z |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |

or 

| time | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_2| ... | ... | ... | ... | ... | ... |
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_1| ... | ... | ... | ... | ... | ... |

I would say the first option (one file per sensor) is more general. The second one is used if all the sensors in the tesbed shares the same acquisition interface which it is not quite common (if differet interfaces, then you wouldneed some SW to mix the data).

_Originally posted by @alfonsotecnalia in https://github.com/aremazeilles/eurobench_documentation/pull/26#issuecomment-608326430_

**Comment by m-lancini** [comment]
> What do we do in scenarios which contains multiple force sensors?
> * One file per sensor: subject_N_run_R_wrench_sensor_1.csv, 

Just to make sure "wrench_sensor_1" will be replaced by the specific measurement instrument name? like subject_N_run_R_left_crutch.csv?

**Comment by alfonsotecnalia** [comment]
Yes. It should be a meaningful ID/name or a serial/number (if it had)

**Comment by aremazeilles** [comment]
I think we should be compatible with option 1 and 2. For 2 I agree that the acquisition timestamp should be shared across all stored data.

**Comment by aremazeilles** [comment]
> > What do we do in scenarios which contains multiple force sensors?
> > 
> > * One file per sensor: subject_N_run_R_wrench_sensor_1.csv,
> 
> Just to make sure "wrench_sensor_1" will be replaced by the specific measurement instrument name? like subject_N_run_R_left_crutch.csv?

I would keep the type in the name: `subject_N_run_R_force_id`.
And for joint file (option_2), use similar id: `id_force_x, id_force_y`

**Comment by aremazeilles** [comment]
Do we agree on the last proposal? I would rather use an id (number) or label (text) to differentiate the different sensor files or column in the joint file. The serial number can be problematic, if you are not using the same device.

**Comment by alfonsotecnalia** [comment]
> I would keep the type in the name: `subject_N_run_R_force_id`.
> And for joint file (option_2), use similar id: `id_force_x, id_force_y`

I agree. To sum up:
- **name of the file**: subject_N_run_R_wrench_tagOrID if we have files from different sensors and  subject_N_run_R_wrench if only one file containing the info of all the sensors.
- **content**: 
| time | tagOrID1_force_x | tagOrID1_force_y | tagOrID1_force_z | tagOrID1_torque_x | tagOrID1_torque_y | tagOrID1_torque_z | ...| tagOrIDN_force_x | tagOrIDN_force_y | tagOrIDN_force_z |tagOrIDN_torque_x | tagOrIDN_torque_y | tagOrIDN_torque_z |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |


  - multiple sensor:

**Comment by m-lancini** [comment]
I'd go for tags or label, IDs could be tricky to handle...
for me Alfonso summary is ok
