### ISSUE TITLE
Separator character(s) in csv files

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/eurobench_documentation#28]
I think a separator character for the fields in the csv files has to be defined

**Comment by m-lancini** [comment]
I'd go for the semicolon, to avoid confusion with some decimal separators.
PS: the decimal separator should be "." for everybody, but for some software with localisation 1.2,3.4 could be ambiguous

**Comment by alfonsotecnalia** [comment]
I'm fine with it

**Comment by aremazeilles** [comment]
Me to
