### ISSUE TITLE
Empty fields

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/eurobench_documentation#29]
At this moment we have Wrench format but maybe some sensors only provide force information (no torque). What has to be inserted in the torque fields? More generic: What has to be inserted in those fields a sensor does not have information to fill?
- NaN
- Empty/blank
- 0

I am in favour of using empty/blank because 0 could lead to confusion (it could be a .0 measurement) and 0/Nan applies to scalar fields (not used for strings)

**Comment by m-lancini** [comment]
blank works for me

**Comment by aremazeilles** [comment]
If we agree with the column labels, then, if a column has no data, I would not put the column in the file.

For the case you suggest, if only force is acquired, and no torque, I would only use columns `time, force_x, force_y, force_z`.

Similar issue could occur with joint angles or joint torques .... We will provide a model with all possible labels, but  if an experiment does not record a given joint, I think it is useless to place that column in the file.
Also it could help for verification in the PI algorithm. If an algo needs a given column, let's say `torque_y`, the algo can verify that `torque_y` column is present in the datafile. If it is not, it can directly return an error code.

**Comment by m-lancini** [comment]
That would be even better. The file could be just a subset of the required columns.

**Comment by alfonsotecnalia** [comment]
I agree
