### ISSUE TITLE
PI algo input and output

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/eurobench_documentation#38]
While the PI algo is crucial for us, its description is split in between two files, the one related to the [template](https://github.com/aremazeilles/eurobench_documentation/blob/master/template.adoc#41-output-type-field), and the one related to the [PI spec](https://github.com/aremazeilles/eurobench_documentation/blob/master/pi_spec.adoc#32-output-data).

We should only have one (in PI spec I think), and the other doc should point to it.

We should also detail all possibilities (PI type), and also comment on the difference in between a run PI, and an experiment PI.

**Comment by alfonsotecnalia** [comment]
I agree. Yesterday I did not find the link with the info to send to Joao easily
