### ISSUE TITLE
Add ECG data

### ISSUE THREAD

**Issue by FraCampus** [aremazeilles/eurobench_documentation#50]
File containing ECG data to be included as a new pre-processed data format.

We think that .CSV file may work, expecting to have a structure like: 
timestamp (sec) ; ECG value

@aremazeilles @NevioTag

**Comment by FraCampus** [comment]
ping @ileniapecoraro5

**Comment by aremazeilles** [comment]
If you can provide a description in the same spirit as the other, I can revise it. Otherwise, you would have to wait that I find some time to propose a description :)

**Comment by FraCampus** [comment]
For sure!

**ECG data**

**Description:** This file shall contain the ECG signal collected from the human subject. Generally, it is a graph of voltage versus time of the electrical activity of the heart using electrodes placed on the skin [en.wikipedia.org/wiki/Electrocardiography](url). Unit is mV (milliVolt). Label: ecg

**Name of the file:** subject_N_run_R_ecg, where N = subject’s number and R = run number. Use appropriate leading zeros for R and N to ensure proper ordering of files.

**File format**: .csv

**File structure:**
time | ecg
sec | mV

Thanks

**Comment by alfonsotecnalia** [comment]
There is a format for physiological data. Wouldn't it be better to include ecg as a field in it?

**Comment by FraCampus** [comment]
We decide to include ECG data as a new Data Format cause it is acquired at a different frequency and cannot be merged with the other ones. Moreover, we cannot neither resample it given that in the benchmarking routine it undergoes frequency analysis.

**Comment by aremazeilles** [comment]
If it is a common practice to have it acquired separately then it makes sense to store it separately. 
If it could be acquired jointly (apart from your testbed @FraCampus ), then we could describe it jointly, mentioning clearly that each of the signal could be also be stored individually if frequency acquisition differs.
