### ISSUE TITLE
Angular Momentum around the Center of Mass

### ISSUE THREAD

**Issue by m-lancini** [aremazeilles/eurobench_documentation#53]
is it referred to a single body (the whole body) or to each segment? in which reference frame? if it's referred to multiple segments each should be referred to its specific, non-fixed, reference system. I think the description is not clear enough here

**Comment by aremazeilles** [comment]
@SjoerdBruijn could you comment on this?

**Comment by SjoerdBruijn** [comment]
This should be the total body angular momentum, around the total body center of mass, expressed in global coordinates. That is, the sum of the angular momenta of different segments around the total body CoM. Is this clear enough?

**Comment by aremazeilles** [comment]
Should we insert these comments in the description?

**Comment by SjoerdBruijn** [comment]
I think that would make sense, if this variable is indeed included. I have tried to tag @nickkluft here in vain. He's the one doing most of the heavy lifting on the programming side. Can somebody add him to the discussion (if still needed)

**Comment by aremazeilles** [comment]
@SjoerdBruijn, I would think that if you copy properly his github ID in your post, as you did, he should receive the message. 
@nickkluft, if you receive this, could you post an acknowledgment here?

**Comment by nickkluft** [comment]
> This should be the total body angular momentum, around the total body center of mass, expressed in global coordinates. That is, the sum of the angular momenta of different segments around the total body CoM. Is this clear enough?

@SjoerdBruijn, this is how I calculated the angular momentum, indeed. 

If further clarification is needed, I would like to refer to Eq. 16 in _Hugh H., and Popovic M., Angular momentum in human walking, Volume 211, Issue 4, (2008)_, or to the methods section of _Bradford C. Bennett, Shawn D. Russell, Pradip Sheth, Mark F. Abel, Angular momentum of walking at different speeds, Human Movement Science, Volume 29, Issue 1 (2010)_

Is this the kind of acknowledgement you were waiting for?

**Comment by aremazeilles** [comment]
So I would propose the following description, gthering the current text, the contribution of @SjoerdBruijn , and the reference provided by @nickkluft 

The angular momentum of a body is a vector quantity that represents the magnitude and the direction in which the body rotates about a reference point [Bennett2010]. We refer here to the total body angular momentum, around the total body Center of Mass (CoM), expressed in global coordinates. That is, the sum of the angular momenta of different segments around the total body CoM (see eq. (16) in [Hugh2010]).

[Hugh2010] Hugh H., and Popovic M., Angular momentum in human walking, Volume 211, Issue 4, (2008), or to the methods section of Bradford C. Bennett, Shawn D. Russell, Pradip Sheth, Mark F. Abel, Angular momentum of walking at different speeds, Human Movement Science, Volume 29, Issue 1 (2010)

**Comment by SjoerdBruijn** [comment]
Sounds good to me. 
S
