### ISSUE TITLE
Add options in the Human Factor Metrics- Meta Data File structure

### ISSUE THREAD

**Issue by FraCampus** [aremazeilles/eurobench_documentation#58]
Dear all,
we noticed that in the Human Factor Meta Data file, the one containing the specification of each question of the questionnaire, there are still missing some options for the type 'likert'. In particular, we want to include also **'ghost/control/reverse likert'.**

(@aremazeilles during one of our last discussions we suggested to insert one column with a boolean value: ghost/control, but this is not feasible given that the options would be three (ghost-control-neitherofthetwo) )

@NevioTag

**Comment by aremazeilles** [comment]
Now you mention three options right? Ghost, control, reverse likert. 
What would be your suggestion then?

I am not against adding such information, stating it as optional.

**Comment by FraCampus** [comment]
Our suggestion, as mentioned above, is to include  **ghost/control/reverse likert** as _'likert'_ type options of the data structure.

In this way, we will have the possibility to define a question as:
- likert
-reverse likert
-ghost likert
-control likert

**Comment by FraCampus** [comment]
Dear @aremazeilles , as discussed in our last meeting in July, we envisioned to propose the following modifications in the **Factor Meta Data File**:

-include the '_reverse likert_' in the ' _likert_ ' type option
-**add one column** in order to include other item details (ghost, control,nothing) and name it **'optional'**

Thanks
@NevioTag
