### ISSUE TITLE
Anthropomorphic, humanoid and testbed file class

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/eurobench_documentation#6]
from Nevio:

> I am not sure if this file, the "Humanoid anthropometric measures" file and the "Testbed-related data" file should be included in the "Pre-Processed Data Files" class or in a different class of files.

**Comment by aremazeilles** [comment]
ping @alfonsotecnalia  @flxalr @DavidPintoFernandez @alfonsotecnalia 

I think Nevio remarks is very relevant: it might be good making distinction in between these different types of file. We would thus have:

* _bipedal system specification_: we are targetting the use of `urdf` file for describing any robotic system, and also human subjects
* _testbed configuration_: that could be related to the `controlled variables` defined in the protocol sheet. I assume yaml structure could be used for such configuration information. Also, this file can be common for all experimental run, but also, in other case, associated to a subset of runs.
* _Pre-processed data_: data captured during the experimentation. Mainly by sensors, but not necessarily only. I think such files are all likely to be timestamped. 


Would this make sense to you?

**Comment by DavidPintoFernandez** [comment]
I agree. I also see that bipedal system's specifications and testbed's configuration could be the same for different experiments and runs, but as I see, pre-processed data has to be different in all runs, it makes sense to not include all in the same group.

**Comment by aremazeilles** [comment]
The other, does this dinstinction bipedal system, testbed configuration and pre-processed data makes sense? If yes, I would then split the documentation into these 3 (new) subsections.

**Comment by flxalr** [comment]
I agree with the proposed separation of file types. In fact, we are currently implementing it exactly as you described it, @aremazeilles.

**Comment by aremazeilles** [comment]
Ok, perfect. I will work on that as soon as I can

**Comment by aremazeilles** [comment]
You can have a look at #33.
