### ISSUE TITLE
Add jointStates format

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/eurobench_documentation#61]
It would consist on the following columns:

- time (s)
- label_1_position (rad)
- label_1_velocity (rad/s)
- label_1_acceleration (rad/s^2)
- ....
- label_N_position (rad)
- label_N_velocity (rad/s)
- label_N_acceleration (rad/s^2)

**Comment by alfonsotecnalia** [comment]
@aremazeilles if you agree, I will add it

**Comment by aremazeilles** [comment]
I placed a thumb up and then the label agree. So I agree.
