### ISSUE TITLE
Addition of feet markers' trajectories (unique to Irreguar Terrains)

### ISSUE THREAD

**Issue by AdrianaTorres** [aremazeilles/eurobench_documentation#67]
For the calculation of a PI (margin of stability) in the irregular terrain testbed the addition of the trajectories of four markers. The file can follow the same format as the one for the joint trajectories: it can be a csv with three collumns (x, y, z) per feet marker (rhee, lhee, rtoe, ltoe, rfootc1, lfootc1, rfootc2, lfootc2).

**Comment by aremazeilles** [comment]
ping @alfonsotecnalia 

This is not specific to irregular terrains, as udbenchmark is requesting to save position of specific markers (see [here](https://github.com/nickkluft/udbenchmark_PIs/issues/7#issuecomment-700000527)).

Is your `rhee` or  `lhee` related to the ` hell` landmark Nick is proposing there?

I see two possibilities:

* define a specific foot landmark format, if all these markers are standard on the foot.
* define a generic landmark / marker position file, in which anyone could define the position of any marker position.

opinion?

Second question: do we accept missing joint position and marker position, or do we explicitly require to separate these 2 files? I would rather be permissive there, but we can discuss it.

In any case, @AdrianaTorres , I would suggest to use for landmark name something like `{l,r}_[landmarkname]_{x,y,z}`, i.e use something like `r_toe_x`, `r_toe_y`, `r_toe_z`

**Comment by AdrianaTorres** [comment]
Our rhee and lhee are the same Nick is proposing, but our rtoe and ltoe do not exactly coincide (Nick places them at the tip of the second finger while we put it in the metatarsal of that finger).

I think it is better to define a generic landmark / marker position file in which each scenario introduces the markers needed. I think it is very difficult to define a specific foot landmark format that meets the needs of everybody. Also, each scenario will need the trajectory of different markers (that may be placed in a different position than in other scenarios) to make their PIs calculation, so having a file where everybody can choose what markers are needed will be the most useful solution. As long as they follow the same nomenclature (for example {l, r}_landmarkname_{x, y, z}) I think it is ok.

Regarding missing joint position and marker position, I think it is ok to put them in the same file. In the end, despite the joint markers are placed in joints and the others don't, they are all markers and the trajectories are given in the same format (x, y, z axis).

Yes, I was referring to name it that way but I may have explained myself badly.

**Comment by aremazeilles** [comment]
So to make it simple, we could add in the Joint trajectories description, at the end something like:

In the case the protocol requires tracking specific landmarks on the subject body, these landmarks can be added to that file, assuming that the protocol documentation provides the landmark label , and a clear description of the landmark position on the subject body.

What do you think @alfonsotecnalia and @AdrianaTorres ?

**Comment by alfonsotecnalia** [comment]
> In the case the protocol requires tracking specific landmarks on the subject body, these landmarks can be added to that file, assuming that the protocol documentation provides the landmark label , and a clear description of the landmark position on the subject body.

I find this paragraph ok.

**Comment by AdrianaTorres** [comment]
ping @aremazeilles
