### ISSUE TITLE
Addition of gait parameters

### ISSUE THREAD

**Issue by AdrianaTorres** [aremazeilles/eurobench_documentation#68]
It would be great to add a file containing the gait parameters. It can be a yaml file:
Gait parameters:
    -  Left Cadence:
       Left Walking Speed:
       Left Stride Time:
       Left Step Time:
       Left Stride Length:
       Left Step Length:
       Left Step Width:
       Left Single Support:
       Rigth Cadence:
       Rigth Walking Speed:
       Rigth Stride Time:
       Rigth Step Time:
       Rigth Stride Length:
       Rigth Step Length:
       Rigth Step Width:
       Rigth Single Support:
       Double Support:

**Comment by aremazeilles** [comment]
We already have the [gait event format](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#gait-events-file). 

The labels you propose sound like iformation that is considered as PI output in some project (and actually the first [csic code](https://github.com/eurobench/pi_octave_csic/tree/master/tests/data/output) we looked at,
But in your case, all this information would be considered as an input file for computing other metrics, is that correct?

Would extending the table 12 make sense to you then?

As the table gets larger, I would suggest then to provide a signification to all the events inserted.. What do you think?

ping @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
I do not see as an extension of table 12. 
I assume these values are inputs for your metrics, are they? Do you compute these values? Could they be considered as final performance indicators? 
If they are inputs for your metrics then I would recommend to create another input type. If you calculate them in a previous process and they can be considered as final performance indicators, then I would also recommend your process to generate one output file file per value (scalar) or one output file with all the values (vector) following the [output formats](https://github.com/aremazeilles/eurobench_documentation/blob/master/pi_spec.adoc#output-data) defined by Eurobench. Then gather the values in a file (which format is the one to be defined) that will be the input for the second process.

**Comment by aremazeilles** [comment]
@AdrianaTorres could you clarify if they are effectively input data you use to compute other metrics, or whether they are indeed PI output?

**Comment by AdrianaTorres** [comment]
They are not PIs, they are used as the input for the calculation of several PIs. We use Vicon to collect the data and we do a preprocessing with their software in order to get gait events, gait parameters and joint angles, forces and moments. Then we use these metrics for PIs calculation.
I also do not see gait parameters as an extension of the gait events table.

**Comment by alfonsotecnalia** [comment]
Is the preprocessing done for each of the runs or is it calculated once per subject and kept constant for different runs involving the same subject?

**Comment by alfonsotecnalia** [comment]
Ok. Then I think we should incorporate this format.

**Comment by aremazeilles** [comment]
@AdrianaTorres could you provide some text describing this new format? If you are not familiar with asciidoc, you could provide me the text to be put in each item, i.e

* a general description (with some reference if it makes sense)
* the file structure. 
I assume the file structure is the one provided at the beginning of your issue. we would need to detail for each key the expected info, with its unit.

Can you do so?

**Comment by AdrianaTorres** [comment]
I have never worked with asciidoc, but the file structure is the one I explained in the first issue. I can send you an example of this file but it is basically a yaml file with a list of the gait parameters and their values. 
I don't  know if I correctly understood what you are asking me to do. When you say if I can give a file description do you mean to explain what gait parameters are and a brief explanation of each of them?

**Comment by aremazeilles** [comment]
Could have a look at the [proposed description](https://github.com/aremazeilles/eurobench_documentation/blob/f_68_gait_parameters/data_format.adoc#611-gait-parameter-file)

I suggest placing left & right as suffix, to be consistent with others, but we can change. 
Could you extend @AdrianaTorres for each item the type and unit (if you answer copying you initial list, and complete aside with the type and unit, I can fill the table)? 

> I have never worked with asciidoc, 

When you visualize the page, click above on `raw`, then you can search for this section. 
The table is written this way:

```
[[tab:gait_param]]
.List of gait events and its considered labelling and units
[options="header"]
|====================
| Gait Event  | Label | type | unit
| Left Cadence | `cadence_left` | tobedef|
| Left Walking Speed | `walking_speed_left`| scalar?|
| Left Stride Time | `stride_time_left`| |
| Left Step Time | `step_time_left`| |
| Left Stride Length | `stride_length_left`| |
| Left Step Length | `step_length_left`| |
| Left Step Width | `step_width_left`| |
| Left Single Support | `single_suport_left`| |
| Right Cadence | `cadence_right` | tobedef|
| Right Walking Speed | `walking_speed_right`| scalar?|
| Right Stride Time | `stride_time_right`| |
| Right Step Time | `step_time_right`| |
| Right Stride Length | `stride_length_right`| |
| Right Step Length | `step_length_right`| |
| Right Step Width | `step_width_right`| |
| Right Single Support | `single_suport_right`| |
| Double Support | `double_support`| |
|====================
```
Symbol `|` is used to distinguish each column, one line per row

**Comment by aremazeilles** [comment]
ping @AdrianaTorres to complete this, I need you to provide me for each item the type (all scalar maybe?), and the unit.

**Comment by AdrianaTorres** [comment]
Here you have the table with the missing data, is this enough or should I specify/do something more?

[[tab:gait_param]]
.List of gait events and its considered labelling and units
[options="header"]
|====================
| Gait Event  | Label | type | unit
| Left Cadence | `cadence_left` | scalar | steps/min
| Left Walking Speed | `walking_speed_left`| scalar | m/s
| Left Stride Time | `stride_time_left`| scalar | s
| Left Step Time | `step_time_left`| scalar | s
| Left Stride Length | `stride_length_left`| scalar | m
| Left Step Length | `step_length_left`| scalar | m
| Left Step Width | `step_width_left`| scalar | m
| Left Single Support | `single_suport_left`| scalar | s
| Right Cadence | `cadence_right` | scalar | steps/min
| Right Walking Speed | `walking_speed_right`| scalar | m/s
| Right Stride Time | `stride_time_right`| scalar | s
| Right Step Time | `step_time_right`| scalar | s
| Right Stride Length | `stride_length_right`| scalar | m
| Right Step Length | `step_length_right`| scalar | m
| Right Step Width | `step_width_right`| scalar | m
| Right Single Support | `single_suport_right`| scalar | s
| Double Support | `double_support`| scalar | s
|====================
